/**
 * Cross-language crypto test vector validation — KIN-428 (CS.1–CS.5).
 *
 * Validates that the Deno crypto port produces bit-exact output matching Python.
 * Run: deno run test-vectors/validate_test_vectors.ts
 *
 * Vectors generated by: python test-vectors/generate_test_vectors.py
 */

import { byteaToUint8Array, bytesToHex, decryptApiKey, deriveUserKeyBits } from "../crypto.ts";

// Test vectors from Python (source of truth)
const vectors = {
  master_key_b64: "dGVzdC1tYXN0ZXIta2V5LTMyLWJ5dGVzIQ==",
  user_id: "550e8400-e29b-41d4-a716-446655440000",
  plaintext: "sk-test-1234567890abcdef",
  nonce_hex: "aabbccddeeff00112233aabb",
  derived_key_hex:
    "1766c7925aa1169295313eac2d59e5222e7edeac0d4a2c3789d209adcb9cf4f1",
  ciphertext_hex:
    "ef36e9e2c09f8da12d25085a0c79a0865bb85ec5546ce5a17638cf717db522403fa9612441771658",
  bytea_ciphertext:
    "\\xef36e9e2c09f8da12d25085a0c79a0865bb85ec5546ce5a17638cf717db522403fa9612441771658",
  bytea_nonce: "\\xaabbccddeeff00112233aabb",
};

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
  }
  return bytes;
}

let passed = 0;
let failed = 0;

function check(name: string, actual: string, expected: string): void {
  if (actual === expected) {
    console.log(`  ✓ ${name}`);
    passed++;
  } else {
    console.error(`  ✗ ${name}`);
    console.error(`    expected: ${expected}`);
    console.error(`    actual:   ${actual}`);
    failed++;
  }
}

console.log("KIN-428 Cross-Language Crypto Test Vectors\n");

// Decode master key
const masterKey = Uint8Array.from(atob(vectors.master_key_b64), (c) =>
  c.charCodeAt(0)
);

// Test 1: HKDF key derivation matches Python
console.log("1. HKDF-SHA256 Key Derivation");
const derivedBits = await deriveUserKeyBits(masterKey, vectors.user_id);
check(
  "Derived key matches Python",
  bytesToHex(derivedBits),
  vectors.derived_key_hex
);

// Test 2: AES-256-GCM decryption matches Python
console.log("\n2. AES-256-GCM Decryption");
const ciphertext = hexToBytes(vectors.ciphertext_hex);
const nonce = hexToBytes(vectors.nonce_hex);
const decrypted = await decryptApiKey(ciphertext, nonce, masterKey, vectors.user_id);
check("Decrypted plaintext matches", decrypted, vectors.plaintext);

// Test 3: byteaToUint8Array parses \x-prefixed hex
console.log("\n3. Bytea Parsing");
const parsedCiphertext = byteaToUint8Array(vectors.bytea_ciphertext);
check(
  "bytea ciphertext parse (\\x prefix)",
  bytesToHex(parsedCiphertext),
  vectors.ciphertext_hex
);

const parsedNonce = byteaToUint8Array(vectors.bytea_nonce);
check(
  "bytea nonce parse (\\x prefix)",
  bytesToHex(parsedNonce),
  vectors.nonce_hex
);

// Test 4: Plain hex (no prefix) also works
console.log("\n4. Plain Hex Parsing (fallback)");
const parsedPlainHex = byteaToUint8Array(vectors.nonce_hex);
check(
  "Plain hex parse (no prefix)",
  bytesToHex(parsedPlainHex),
  vectors.nonce_hex
);

// Test 5: Full round-trip — bytea parse → decrypt
console.log("\n5. Full Round-Trip (bytea → decrypt)");
const roundTripDecrypted = await decryptApiKey(
  parsedCiphertext,
  parsedNonce,
  masterKey,
  vectors.user_id
);
check("Round-trip decrypt matches", roundTripDecrypted, vectors.plaintext);

// Summary
console.log(`\n${"=".repeat(40)}`);
console.log(`Results: ${passed} passed, ${failed} failed`);
if (failed > 0) {
  console.error(
    "\nFAILED — Deno crypto port does not match Python. Check salt handling."
  );
  Deno.exit(1);
} else {
  console.log("\nPASSED — Deno crypto port is bit-exact with Python.");
}
